package miterenewed.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.SimpleFabricLootTableSubProvider;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.providers.number.ints.ContextIntProvider;
import net.minecraft.world.level.storage.loot.providers.number.ints.ContextIntProviders;
import org.jetbrains.annotations.NotNull;

import java.util.concurrent.CompletableFuture;
import java.util.function.BiConsumer;

public class MITERenewedChestLootTableProvider extends SimpleFabricLootTableSubProvider {
    private final Holder<ContextIntProvider> binomialRolls = ContextIntProviders.binomial(10, 0.4f);
    public MITERenewedChestLootTableProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(output, registryLookup, LootContextParamSets.CHEST);
    }

    @Override
    public void run() {
        // Unused: Fabric datagen drives generation through generate(BiConsumer)
    }

    @Override
    public void generate(@NotNull BiConsumer<ResourceKey<LootTable>, LootTable.Builder> lootTableBiConsumer) {
        lootTableBiConsumer.accept(BuiltInLootTables.SPAWN_BONUS_CHEST, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.SAND)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,5))))
                        .add(LootItem.lootTableItem(Items.CARROT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.POTATO)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BEETROOT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_ARMORER, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_HELMET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.IRON_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_BUTCHER, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.SUSPICIOUS_STEW)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.RED_MUSHROOM)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BROWN_MUSHROOM)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.MUTTON)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_CARTOGRAPHER, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.PAPER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.MAP)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_FISHER, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.SALMON)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_FLETCHER, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.FEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.ARROW)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_MASON, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.CLAY_BALL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                        .add(LootItem.lootTableItem(Items.STONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                        .add(LootItem.lootTableItem(Items.FLOWER_POT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_SHEPHERD, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_TANNERY, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_BOOTS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.SADDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_TEMPLE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,2))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.REDSTONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_TOOLSMITH, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.WOODEN_SHOVEL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_WEAPONSMITH, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.WOODEN_SWORD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_DESERT_HOUSE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.CACTUS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DEAD_BUSH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BOOK)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_PLAINS_HOUSE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BOOK)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.OAK_SAPLING)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.APPLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_SAVANNA_HOUSE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.BUNDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BOOK)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ACACIA_SAPLING)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.TORCH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_SNOWY_HOUSE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.BOOK)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.POTATO)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.TORCH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.SNOWBALL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.VILLAGE_TAIGA_HOUSE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.DIRT)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.BOOK)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_PIE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.SPRUCE_SAPLING)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.FERN)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.JUNGLE_TEMPLE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.IRON_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.DESERT_PYRAMID, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.IRON_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.SHIPWRECK_TREASURE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.IRON_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.SHIPWRECK_SUPPLY, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.SHIPWRECK_MAP, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.IRON_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.GOLD_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.IGLOO_CHEST, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.RUINED_PORTAL, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.UNDERWATER_RUIN_SMALL, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.UNDERWATER_RUIN_BIG, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.DESERT_PYRAMID_ARCHAEOLOGY, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.DESERT_WELL_ARCHAEOLOGY, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.OCEAN_RUIN_COLD_ARCHAEOLOGY, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.OCEAN_RUIN_WARM_ARCHAEOLOGY, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.TRAIL_RUINS_ARCHAEOLOGY_COMMON, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.TRAIL_RUINS_ARCHAEOLOGY_RARE, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));

        lootTableBiConsumer.accept(BuiltInLootTables.SIMPLE_DUNGEON, LootTable.lootTable()
                .withPool(LootPool.lootPool()
                        .setRolls(binomialRolls)
                        .add(LootItem.lootTableItem(Items.WHEAT_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.between(1,4))))
                        .add(LootItem.lootTableItem(Items.PUMPKIN_SEEDS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COAL)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.BONE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.ROTTEN_FLESH)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_NUGGET)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.EMERALD)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_CHESTPLATE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.LEATHER_LEGGINGS)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.SADDLE)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.COPPER_HORSE_ARMOR)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.DIAMOND_HORSE_ARMOR)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.IRON_HORSE_ARMOR)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                        .add(LootItem.lootTableItem(Items.GOLDEN_HORSE_ARMOR)
                                .apply(SetItemCountFunction.setCount(ContextIntProviders.exactly(1))))
                ));
    }

}
